"""Main Cobasket dashboard with a guided discovery-to-report workflow."""

from __future__ import annotations

from pathlib import Path
import sys

from PyQt6.QtWidgets import QApplication, QMenu

from .editable_dashboard import EditableCobasketDashboard
from .workflow_dialog import WorkflowDialog


class GuidedCobasketDashboard(EditableCobasketDashboard):
    """Editable dashboard with a first-class guided analysis workflow."""

    def __init__(self) -> None:
        super().__init__()
        workflow_menu = QMenu("Workflow", self)
        before = self.menuBar().actions()[0] if self.menuBar().actions() else None
        self.menuBar().insertMenu(before, workflow_menu)
        guided_action = workflow_menu.addAction("Guided discovery → report…")
        guided_action.triggered.connect(self.open_guided_workflow)
        self._workflow_dialog: WorkflowDialog | None = None

    def open_guided_workflow(self) -> None:
        """Open the normal Cobasket discovery, validation, calibration, and report path."""
        config_path = self._configuration_path()
        workspace = config_path.parent if config_path is not None else Path.cwd()
        dialog = WorkflowDialog(workspace, self)
        dialog.portfolio_ready.connect(self._workflow_portfolio_ready)
        dialog.report_ready.connect(self._workflow_report_ready)
        dialog.finished.connect(lambda _: setattr(self, "_workflow_dialog", None))
        self._workflow_dialog = dialog
        dialog.show()

    def _workflow_portfolio_ready(self, path: str) -> None:
        """Select a portfolio generated or updated by the guided workflow."""
        self.path_edit.setText(path)
        self.status_label.setText("Guided workflow portfolio selected. Edit holdings or run analysis as needed.")

    def _workflow_report_ready(self, path: str) -> None:
        """Load a report generated by the guided workflow into the dashboard."""
        self.report_path_edit.setText(path)
        self.load_report()


def main() -> None:
    """Launch the guided Cobasket dashboard."""
    app = QApplication(sys.argv)
    window = GuidedCobasketDashboard()
    window.show()
    raise SystemExit(app.exec())
