"""Main Cobasket dashboard with a guided discovery-to-report workflow."""

from __future__ import annotations

from pathlib import Path
import sys

from PyQt6.QtWidgets import QApplication, QGroupBox, QHBoxLayout, QLabel, QMenu, QPushButton

from .editable_dashboard import EditableCobasketDashboard
from .workflow_dialog import WorkflowDialog


class GuidedCobasketDashboard(EditableCobasketDashboard):
    """Recommendation dashboard with a first-class workspace workflow."""

    def __init__(self) -> None:
        super().__init__()
        self.sources_group.setVisible(False)

        workflow_menu = QMenu("Workspace", self)
        self.menuBar().insertMenu(self.menuBar().actions()[0], workflow_menu)
        guided_action = workflow_menu.addAction("Open / update workspace…")
        guided_action.triggered.connect(self.open_guided_workflow)
        workflow_menu.addSeparator()
        manual_action = workflow_menu.addAction("Show manual file controls")
        manual_action.setCheckable(True)
        manual_action.toggled.connect(self.sources_group.setVisible)

        workspace_box = QGroupBox("Workspace")
        workspace_layout = QHBoxLayout(workspace_box)
        workspace_text = QLabel(
            "Normal use starts here. Cobasket will inspect an empty, partial, or existing workspace "
            "and show the next recommended step."
        )
        workspace_text.setWordWrap(True)
        workspace_button = QPushButton("Open / update workspace…")
        workspace_button.clicked.connect(self.open_guided_workflow)
        workspace_layout.addWidget(workspace_text, 1)
        workspace_layout.addWidget(workspace_button)
        self.centralWidget().layout().insertWidget(0, workspace_box)

        self._workflow_dialog: WorkflowDialog | None = None

    def open_guided_workflow(self) -> None:
        """Open the normal Cobasket discovery, validation, calibration, and report path."""
        config_path = self._configuration_path()
        workspace = config_path.parent if config_path is not None else Path.cwd()
        dialog = WorkflowDialog(workspace, self)
        dialog.portfolio_ready.connect(self._workflow_portfolio_ready)
        dialog.report_ready.connect(self._workflow_report_ready)
        dialog.finished.connect(lambda _: setattr(self, "_workflow_dialog", None))
        self._workflow_dialog = dialog
        dialog.show()

    def _workflow_portfolio_ready(self, path: str) -> None:
        """Select a portfolio generated or updated by the workspace workflow."""
        self.path_edit.setText(path)
        self.status_label.setText("Workspace selected. Use the workspace window for the next recommended step.")

    def _workflow_report_ready(self, path: str) -> None:
        """Load a report generated by the workspace workflow into the dashboard."""
        self.report_path_edit.setText(path)
        self.load_report()


def main() -> None:
    """Launch the guided Cobasket dashboard."""
    app = QApplication(sys.argv)
    window = GuidedCobasketDashboard()
    window.show()
    raise SystemExit(app.exec())
